### ISSUE TITLE
cannot see bars even though they are there

### ISSUE THREAD

**Issue by ghost** [karlstav/cava#109]
So I know the bars are there because when I highlight them I can see them moving but I cannot see them without highlighting them, is there anything I can do?

**Comment by karlstav** [comment]
Have you tried changing the color? in the config file or by pressing c/b

**Comment by JackCDK** [comment]
yes I have tried doing that, the background changes color but the bars don't they just stay invisible

**Comment by karlstav** [comment]
what terminal emulator are you using?

**Comment by JackCDK** [comment]
xfce4-terminal

**Comment by karlstav** [comment]
strange, works fine here. Maybe there is an issue with ncurses. What distro are you running?

You could test `method = noncurses` in the output section in the config, to test it without ncurses.

**Comment by JackCDK** [comment]
yeah it's working now, sorry for the late reply

**Comment by Kurtoid** [comment]
How did you resolve the issue, I have the same issue.

**Comment by Kurtoid** [comment]
I also get setterm: terminal xterm does not support --blank
when I scroll back up

**Comment by karlstav** [comment]
@JackCDK any idea how you fixed this?

**Comment by JackCDK** [comment]
All I did was purge xfce4-terminal and reinstall it again, sorry it's vague but that worked for me

**Comment by itsmewallis** [comment]
Encountered this issue on Slackware. Upon terminating the app I see this in the console:
'
[~]$ cava

setterm: terminal xterm-256color does not support --blank
`

**Comment by karlstav** [comment]
@itsmewallis I wouldn't worry about that message, when cava is in tty mode it disables blanking (`setterm -blank 0`), when it existis it turns blanking back on (`setterm -blank 10`), however I have not been able to pass the `inAtty` variable to the exit function so it runs the `setterm -blank 10` either way.

BTW does it work when you try to run it n a (tty) virtual console ( e.g. ctril+alt+f2)?

**Comment by Kurtoid** [comment]
It works on virtual consoles

**Comment by karlstav** [comment]
Have you tried setting `method = noncurses` in the output section in the config, to test it without ncurses?

**Comment by itsmewallis** [comment]
Yeah I already tried that, didn't see a difference unfortunately. In tty mode, I was able to see the bars, however they were just blue 1's.

**Comment by karlstav** [comment]
see #116 for the issue with the 1's. 

I'm guessing this whole issue has something to do with the xfce desktop environment and its settings for the terminal, have you tried playing around with the color settings in the terminal?

**Comment by greenbigfrog** [comment]
In tty I can see the the bars (`88`s and numbers on top). In my terminal they ain't diplaying though (they are there, I can highlight them). I've tried everything in my power I was able to think off (different terminal emus, other colors, etc.)

Since raw output works I might just attempt writing my own displayer in case we can't get it to work

**Comment by greenbigfrog** [comment]
arch, with i3wm (no DE)

**Comment by karlstav** [comment]
I think the problem might be related to something in  `~/.Xresources` file, could you try to reset all Xresources to default?

**Comment by greenbigfrog** [comment]
that file doesn't even exist on my system...

**Comment by karlstav** [comment]
hmm guess that means that you are running the default settings. I can't seem to find anything common for this bug. The most annoying thing is that I can remember experiencing it myself long ago, but I have forgotten how I fixed it (if I did..), I have also forgotten what system I was running, could have been arch with i3 or could have been xubuntu.

**Comment by greenbigfrog** [comment]
I'm just gonna write my own frontend ;) gives me a nice usefull project to work on
(or are there any other frontends available?)

**Comment by karlstav** [comment]
not that I know off, you could try the gui branch, it is sort of a X frontend

**Comment by itsmewallis** [comment]
I tried it in KDE's Konsole in Plasma 5 as well, issue still occurs.

**Comment by karlstav** [comment]
maybe it is far fetched, but can this be related to #121 ? That was solved by setting the locale:
```
localectl set-locale LANG=en_US.UTF-8
```

**Comment by itsmewallis** [comment]
Locale settings were the issue all along. 

After editing my config, cava works!

Just for future reference, for those on Slackware remember that your locale settings in versions <= 14.2 are set a config that does not support UTF-8 characters by default.. (Eg. LANG=en_US)

Refer to: http://docs.slackware.com/slackware:localization for details on how to enable UTF-8 support. 

Thanks for the pointer.

**Comment by iankay** [comment]
> maybe it is far fetched, but can this be related to #121 ? That was solved by setting the locale:
> 
> ```
> localectl set-locale LANG=en_US.UTF-8
> ```

I'm having this issue as well, but applying the system locale (localectl set-locale LANG=en_US.UTF-8) doesn't do anything. The bars are invisible, unless highlighted. I have tried changing terminals from urxvt to xfce4-terminal, but still get the same issue.

**Comment by Zanark** [comment]
I have the same issue, I tried the same but nothing happened.
I checked the terminal in VSCode and it works fine there.

**Comment by thepont** [comment]
Yea, seems the colors of the terminal are not changing, so that it's just background colour on background colour ?

**Comment by sashgorokhov** [comment]
Had the same issue on Kubuntu 19, Plasma 5 and Konsole.
The problem was in having `LC_ALL` env var empty.

`LC_ALL=en_US.UTF-8 cava` worked for me
